# ==============================
# Global
# ==============================
# Plugin Manager
[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'Shougo/neomru.vim'

# Search Count
[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
  source ~/.config/dein/plugins/vim-anzu.vim
'''

# Visualize Space
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# Filer
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  source ~/.config/dein/plugins/nerdtree.vim
'''
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
[[plugins]]
repo = 'junegunn/fzf.vim'
merged = 0
hook_add = '''
  source ~/.config/dein/plugins/fzf.vim
'''

# Change Pane Size
[[plugins]]
repo = 'simeji/winresizer'

# Google Translate
[[plugins]]
repo = 'skanehira/translate.vim'

# ==============================
# Appearance
# ==============================
# Theme
[[plugins]]
repo = 'flazz/vim-colorschemes'

# Status Bar
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  source ~/.config/dein/plugins/vim-airline.vim
'''
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# Icons
[[plugins]]
repo = 'ryanoasis/vim-devicons'

# Indent
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  source ~/.config/dein/plugins/indentLine.vim
'''

# Syntax Highlight for TOML
[[plugins]]
repo = 'cespare/vim-toml'

# ==============================
# Coding Auxiliary for Common
# ==============================
# Snipet
[[plugins]]
repo = 'SirVer/ultisnips'

# Asynchronous Coding Check
[[plugins]]
repo = 'w0rp/ale'

# Add surrounding character
[[plugins]]
repo = 'tpope/vim-surround'

# Auto Close
[[plugins]]
repo = 'Townk/vim-autoclose'

# Commentout
[[plugins]]
repo = 'tomtom/tcomment_vim'

# Input Completion
[[plugins]]
repo = 'prabirshrestha/async.vim'
[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
[[plugins]]
repo = 'mattn/vim-lsp-settings'

# HTML/CSS Coding Auxiliary
[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = '''
  source ~/.config/dein/plugins/emmet-vim.vim
'''

# Syntax check
[[plugins]]
repo = 'vim-syntastic/syntastic'

# Replacement preview
[[plugins]]
repo = 'markonm/traces.vim'

# Make markdown table
[[plugins]]
repo = 'mattn/vim-maketable'

# Markdown Preview
[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = '''
cd app & yarn install
'''

# ==============================
# Coding Auxiliary for Language
# ==============================
# Ruby
[[plugins]]
repo = 'tpope/vim-endwise'

# Python
[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'

# Terraform
[[plugins]]
repo = 'hashivim/vim-terraform'
hook_add = '''
  source ~/.config/dein/plugins/vim-terraform.vim
'''

# fish
[[plugins]]
repo = 'dag/vim-fish'

# ==============================
# Git
# ==============================
# Git on Vim
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  source ~/.config/dein/plugins/fugitive.vim
'''

# Visualize Change Line for Git
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  source ~/.config/dein/plugins/vim-gitgutter.vim
'''

