# ============================
# Global
# ============================
# Plugin Manager
[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'Shougo/neomru.vim'

# Search Count
[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
  source ~/.config/nvim/plugins/vim-anzu.vim
'''

# Visualize Space
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# Filer
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  source ~/.config/nvim/plugins/nerdtree.vim
'''
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
  source ~/.config/nvim/plugins/fzf.vim
'''

# Change Pane Size
[[plugins]]
repo = 'simeji/winresizer'

# ============================
# Appearance
# ============================
# Theme
[[plugins]]
repo = 'altercation/vim-colors-solarized'
hook_add = '''
  source ~/.config/nvim/plugins/vim-colors-solarized.vim
'''

[[plugins]]
repo = 'flazz/vim-colorschemes'

# Status Bar
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  source ~/.config/nvim/plugins/lightline.vim
'''

# Icons
[[plugins]]
repo = 'ryanoasis/vim-devicons'

# Indent
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  source ~/.config/nvim/plugins/indentLine.vim
'''

# Syntax Highlight
[[plugins]]
repo = 'cespare/vim-toml'

# ============================
# Coding Auxiliary
# ============================
# Auto Close
[[plugins]]
repo = 'Townk/vim-autoclose'

# Auto Insert end for Ruby
[[plugins]]
repo = 'tpope/vim-endwise'

# Commentout
[[plugins]]
repo = 'tomtom/tcomment_vim'

# HTML/CSS Coding Auxiliary
[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = '''
  source ~/.config/nvim/plugins/emmet-vim.vim
'''

# Input Completion
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/deoplete.vim
'''
repo = 'Shougo/neco-vim'
[[plugins]]
repo = 'Shougo/neco-syntax'

# Input Completion for Python
[[plugins]]
repo = 'davidhalter/jedi-vim'
[[plugins]]
repo = 'deoplete-plugins/deoplete-jedi'

# Indent Auxiliary for Python
[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'

# Asynchronous Coding Check
[[plugins]]
repo = 'w0rp/ale'

# ============================
# Git
# ============================
# Git on Vim
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  source ~/.config/nvim/plugins/fugitive.vim
'''

# Visualize Change Line for Git
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  source ~/.config/nvim/plugins/vim-gitgutter.vim
'''

