---
- name: install brew packages
  ignore_errors: true
  homebrew:
    name: "{{ item }}"
    state: present
    update_homebrew: yes
  loop:
    - htop
    - tree
    - watch
    - azure-cli
    - chatgpt
    - grep
    - pgweb
    - postgresql
    - awsdac
    - codex
    - npm
  tags:
    - brew

- name: install cask packages
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
    install_options: force
  loop:
    - google-chrome
    - 1password
    - slack
    - notion
    - anki
    - displaylink
    - logi-options-plus
    - cleanshot
    - discord
    - visual-studio-code
    - intellij-idea
    - claude
    - docker
    - zoom
    - raycast
    - chatgpt-atlas
    - microsoft-office
    - microsoft-teams
  tags:
    - brew

