---
# ==============================
# fish
# ==============================
- name: add fish to /etc/shells
  lineinfile:
    path: /etc/shells
    line: "{{ bin_path }}/fish"
    state: present
  become: yes
  tags:
    - fish

- name: change default shell to fish
  command: chsh -s {{ bin_path }}/fish
  become: yes
  tags:
    - fish

- name: create .config directory
  file:
    path: ~/.config/fish/functions
    state: directory
    mode: 0755
  tags:
    - fish

- name: install fisher
  get_url:
    url: https://git.io/fisher
    dest: ~/.config/fish/functions/fisher.fish
  tags:
    - fish

- name: install fish plugins
  command: fish -C "fisher install {{ item }}"
  loop:
    - jethrokuan/z
    - oh-my-fish/theme-bobthefish
    - jethrokuan/fzf
    - decors/fish-ghq
    - evanlucas/fish-kubectl-completions
  tags:
    - fish

# ==============================
# tmux
# ==============================
- name: install tpm
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
  tags:
    - tmux

# ==============================
# pip
# ==============================
- name: install pip module
  pip:
    name: "{{ item }}"
    executable: pip3
  loop:
    - pep8
    - flake8
    - pylint
    - poetry
    - docker-compose
  tags:
    - pip

- name: add poetry auto complete
  ignore_errors: true
  shell: poetry completions fish > ~/.config/fish/completions/poetry.fish
  tags:
    - pip

# ==============================
# dotfiles
# ==============================
- name: copy dotfiles
  copy:
    src: ../{{ item.file }}
    dest: "{{ item.dest }}"
  loop:
    - { file: ".gitconfig", dest: "~/.gitconfig" }
    - { file: ".vimrc", dest: "~/.vimrc" }
    - { file: ".ideavimrc", dest: "~/.ideavimrd" }
    - { file: ".tmux.conf", dest: "~/.tmux.conf" }
    - { file: "config.fish", dest: "~/.config/fish/config.fish" }
    - { file: "coc-settings.json", dest: "~/.vim/coc-settings.json" }
  tags:
    - dotfiles
