---
- name: add tap repository
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  loop:
    - homebrew/cask-fonts
    - homebrew/cask-drivers
    - gjbae1212/gossm
  tags:
    - package

- name: install brew packages
  ignore_errors: true
  homebrew:
    name: "{{ item }}"
    state: present
    update_homebrew: yes
  loop:
    - git
    - fish
    - vim
    - tmux
    - lazygit
    - lazydocker
    - go
    - nodejs
    - ghq
    - ag
    - fzf
    - awscli
    - github/gh/gh
    - tree
    - htop
    - yarn
    - watch
    - anyenv
    - tflint
    - driftctl
    - act
    - kayac/tap/ecspresso
    - fujiwara/tap/lambroll
    - mysql-client
    - jq
    - fd
    - bat
    - gossm
    - vagrant
    - displaylink
    - gibo
    - act
  tags:
    - package

- name: install cask packages
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
    install_options: force
  loop:
    - font-hack-nerd-font
    - google-chrome
    - intellij-idea
    - 1password
    - postman
    - slack
    - iterm2
    - docker
    - google-japanese-ime
  tags:
    - package

- name: run anyenv init
  command: anyenv install --init
  tags:
    - package

- name: install pip module
  pip:
    name: "{{ item }}"
    executable: pip3
  loop:
    - pep8
    - flake8
    - pylint
    - poetry
  tags:
    - package

- name: add poetry auto complete
  ignore_errors: true
  shell: poetry completions fish > ~/.config/fish/completions/poetry.fish
  tags:
    - package

