---
- name: install brew packages
  homebrew:
    name: "{{ item }}"
    state: present
    update_homebrew: yes
  loop:
    - git
    - fish
    - vim
    - tmux
    - docker
    - lazygit
    - lazydocker
    - go
    - nodejs
    - ghq
    - ag
    - fzf
    - awscli
    - github/gh/gh
    - tree
    - curl
    - htop
    - yarn
    - watch
  tags:
    - package

- name: add tap repository
  homebrew_tap:
    tap: homebrew/cask-fonts
    state: present
  tags:
    - package

- name: install cask packages
  homebrew_cask:
    name: "{{ item }}"
    state: present
    install_options: force
  loop:
    - alfred
    - docker
    - font-hack-nerd-font
    - google-chrome
    - virtualbox
    - vagrant
    - visual-studio-code
  tags:
    - package

