---
- name: Get git repository root
  command: git rev-parse --show-toplevel
  args:
    chdir: "{{ playbook_dir }}"
  register: git_root
  changed_when: false
  tags:
    - tools

- name: install aqua
  homebrew:
    name: aqua
    state: present
    update_homebrew: true
  tags:
    - tools

- name: create directory
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "~/.config/aqua"
    - "~/.config/git"
    - "~/.config/lazygit"
    - "~/.config/ecsta"
    - "~/.claude"
  tags:
    - dotfiles
    - tools

- name: link dotfiles
  file:
    src: "{{ git_root.stdout }}/{{ item.file }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes
  loop:
    - { file: "aqua.yaml", dest: "~/.config/aqua/aqua.yaml" }
    - { file: ".config/lazygit/config.yml", dest: "~/.config/lazygit/config.yml" }
    - { file: ".config/git/ignore", dest: "~/.config/git/ignore" }
    - { file: ".config/ecsta/config.json", dest: "~/.config/ecsta/config.json" }
    - { file: ".claude/settings.json", dest: "~/.claude/settings.json" }
    - { file: ".gitconfig", dest: "~/.gitconfig" }
  tags:
    - dotfiles
    - tools

- name: aqua - install tools
  ansible.builtin.command: aqua i -l
  args:
    chdir: "{{ git_root.stdout }}/"
  tags:
    - tools

- name: aqua - list global tools
  ansible.builtin.command: aqua list -i
  register: aqua_tools
  changed_when: false
  tags:
    - tools

- name: show aqua tools list
  ansible.builtin.debug:
    msg: "{{ aqua_tools.stdout_lines }}"
  tags:
    - tools

