---
- name: update apt repository
  apt_repository:
    repo: "{{ item }}"
  loop:
    - ppa:longsleep/golang-backports
    - ppa:fish-shell/release-3
    - ppa:lazygit-team/release
  tags:
    - package

- name: install apt packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - git
    - fish
    - vim
    - tmux
    - docker
    - lazygit
    - golang-go
    - nodejs
    - awscli
    - tree
    - curl
    - htop
    - silversearcher-ag
    - yarn
  tags:
    - package

- name: install go packages
  command: go get {{ item }}
  loop:
    - github.com/jesseduffield/lazydocker
    - github.com/goccy/go-yaml
    - github.com/x-motemen/ghq
  tags:
    - package

