---
- name: Get git repository root
  command: git rev-parse --show-toplevel
  args:
    chdir: "{{ playbook_dir }}"
  register: git_root
  changed_when: false
  tags:
    - zsh

- name: install zsh package manager
  homebrew:
    name: sheldon
    state: present
    update_homebrew: yes
  tags:
    - zsh

- name: create directory
  file:
    path: "~/.config/{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - sheldon
    - git
  tags:
    - dotfiles
    - zsh

- name: create claude directory
  file:
    path: "~/.claude"
    state: directory
    mode: "0755"
  tags:
    - dotfiles
    - zsh

- name: link dotfiles
  file:
    src: "{{ git_root.stdout }}/{{ item.file }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes
  loop:
    - { file: ".zshrc", dest: "~/.zshrc" }
    - { file: ".p10k.zsh", dest: "~/.p10k.zsh" }
    - { file: ".claude/settings.json", dest: "~/.claude/settings.json" }
    - { file: ".config/git/ignore", dest: "~/.config/git/ignore" }
    - { file: ".config/sheldon/plugins.toml", dest: "~/.config/sheldon/plugins.toml" }
  tags:
    - dotfiles
    - zsh

