# ============================
# Global
# ============================
# Plugin Manager
[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'Shougo/neomru.vim'

# Integration Interface
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  source ~/.vim/dein/plugins/denite.vim
'''

# Search Count
[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
  source ~/.vim/dein/plugins/vim-anzu.vim
'''

# Visualize Space
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# Filer
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  source ~/.vim/dein/plugins/nerdtree.vim
'''

# Change Window Size
[[plugins]]
repo = 'simeji/winresizer'

# ============================
# Appearance
# ============================
# Theme
[[plugins]]
repo = 'altercation/vim-colors-solarized'
hook_add = '''
  source ~/.vim/dein/plugins/vim-colors-solarized.vim
'''

# Status Bar
[[plugins]]
repo = 'vim-airline/vim-airline'

# ============================
# Coding Auxiliary
# ============================
# Auto Close
[[plugins]]
repo = 'Townk/vim-autoclose'

# Auto Insert end for Ruby
[[plugins]]
repo = 'tpope/vim-endwise'

# Give something that encloses the text
[[plugins]]
repo = 'tpope/vim-surround'

# Commentout
[[plugins]]
repo = 'tomtom/tcomment_vim'

# HTML/CSS Coding Auxiliary
[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = '''
  source ~/.vim/dein/plugins/emmet-vim.vim
'''

# Input Completion
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  source ~/.vim/dein/plugins/deoplete.vim
'''
[[plugins]]
repo = 'Shougo/neco-vim'
[[plugins]]
repo = 'Shougo/neco-syntax'
[[plugins]]
repo = 'ujihisa/neco-look'

# Input Completion for Python
[[plugins]]
repo = 'davidhalter/jedi-vim'
[[plugins]]
repo = 'deoplete-plugins/deoplete-jedi'

# Indent Auxiliary for Python
[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'

# Asynchronous Coding Check
[[plugins]]
repo = 'w0rp/ale'

# ============================
# Git
# ============================
# Git on Vim
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  source ~/.vim/dein/plugins/fugitive.vim
'''

# Visualize Change Line for Git
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  source ~/.vim/dein/plugins/vim-gitgutter.vim
'''
