name: Mac OS

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: install ansible
        run: brew install ansible

      - name: install collection with ansible galaxy
        run: ansible-galaxy collection install community.general

      - name: deploy
        run: ansible-playbook -i localhost, -c local ansible/main.yml -K
