name: Installation Test

on:
  push:
    branches:
      - main

jobs:
  MacOS:
    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: initialize
        run: make init

      - name: deploy
        run: make deploy

